# Generated by Django 5.0.2 on 2024-02-14 12:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_category_description_remove_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklynews',
            name='category',
        ),
        migrations.AlterField(
            model_name='category',
            name='add_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dailynews',
            name='date_uploaded',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='newnewsforegin',
            name='date_uploaded',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='politics',
            name='date_uploaded',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vedio',
            name='date_uploaded',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='weeklynews',
            name='date_uploaded',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
